"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssetType = void 0;
var AssetType;
(function (AssetType) {
    AssetType["Image"] = "1";
    AssetType["TeeShirt"] = "2";
    AssetType["Audio"] = "3";
    AssetType["Mesh"] = "4";
    AssetType["Lua"] = "5";
    AssetType["Hat"] = "8";
    AssetType["Place"] = "9";
    AssetType["Model"] = "10";
    AssetType["Shirt"] = "11";
    AssetType["Pants"] = "12";
    AssetType["Decal"] = "13";
    AssetType["Head"] = "17";
    AssetType["Face"] = "18";
    AssetType["Gear"] = "19";
    AssetType["Badge"] = "21";
    AssetType["Animation"] = "24";
    AssetType["Torso"] = "27";
    AssetType["RightArm"] = "28";
    AssetType["LeftArm"] = "29";
    AssetType["LeftLeg"] = "30";
    AssetType["RightLeg"] = "31";
    AssetType["Package"] = "32";
    AssetType["GamePass"] = "34";
    AssetType["Plugin"] = "38";
    AssetType["MeshPart"] = "40";
    AssetType["HairAccessory"] = "41";
    AssetType["FaceAccessory"] = "42";
    AssetType["NeckAccessory"] = "43";
    AssetType["ShoulderAccessory"] = "44";
    AssetType["FrontAccessory"] = "45";
    AssetType["BackAccessory"] = "46";
    AssetType["WaistAccessory"] = "47";
    AssetType["ClimbAnimation"] = "48";
    AssetType["DeathAnimation"] = "49";
    AssetType["FallAnimaiton"] = "50";
    AssetType["IdleAnimation"] = "51";
    AssetType["JumpAnimation"] = "52";
    AssetType["RunAnimation"] = "53";
    AssetType["SwimAnimation"] = "54";
    AssetType["WalkAnimation"] = "55";
    AssetType["PoseAnimation"] = "56";
    AssetType["EarAccessory"] = "57";
    AssetType["EyeAccessory"] = "58";
    AssetType["EmoteAnimation"] = "61";
    AssetType["Video"] = "62";
})(AssetType = exports.AssetType || (exports.AssetType = {}));
//# sourceMappingURL=AssetType.js.map